package at.wifi.swdev.dreieck;

import java.awt.BorderLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class MainFrame extends javax.swing.JFrame {

    private DreieckPanel dreieckPanel;

    public MainFrame() {
        initComponents();
        dreieckPanel = new DreieckPanel();
        pnlZeichnen.add(dreieckPanel, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitelText = new javax.swing.JLabel();
        lblSeiteText = new javax.swing.JLabel();
        txtSeite = new javax.swing.JTextField();
        btnZeichne = new javax.swing.JButton();
        lblHoeheText = new javax.swing.JLabel();
        lblHoehe = new javax.swing.JLabel();
        lblUmfangText = new javax.swing.JLabel();
        lblUmfang = new javax.swing.JLabel();
        lblFlaecheText = new javax.swing.JLabel();
        lblFlaeche = new javax.swing.JLabel();
        pnlZeichnen = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitelText.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        lblTitelText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitelText.setText("Gleichseitiges Dreieck");

        lblSeiteText.setText("Seite");

        txtSeite.setText("0");

        btnZeichne.setText("Berechne und Zeichne");
        btnZeichne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZeichneActionPerformed(evt);
            }
        });

        lblHoeheText.setText("Höhe");

        lblHoehe.setText("0");

        lblUmfangText.setText("Umfang");

        lblUmfang.setText("0");

        lblFlaecheText.setText("Fläche");

        lblFlaeche.setText("0");

        pnlZeichnen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlZeichnen.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlZeichnen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblHoeheText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUmfangText, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(lblFlaecheText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFlaeche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUmfang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblHoehe)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSeiteText, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtSeite, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnZeichne, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblTitelText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitelText)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSeite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSeiteText)
                    .addComponent(btnZeichne))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoeheText)
                    .addComponent(lblHoehe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUmfangText)
                    .addComponent(lblUmfang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFlaecheText)
                    .addComponent(lblFlaeche))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlZeichnen, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(0, 0, 450, 500);
    }// </editor-fold>//GEN-END:initComponents

  private void btnZeichneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZeichneActionPerformed

      int seite = 0;

      try {
          seite = Integer.parseInt(txtSeite.getText());
      } catch (NumberFormatException nfe) {
          JOptionPane.showMessageDialog(this, "Seite kann nicht gelesen werden!", "Parsefehler", JOptionPane.WARNING_MESSAGE);
          return;
      }

      int flaeche = (int) (Math.sqrt(3) / 4 * seite * seite);
      int umfang = seite * 3;
      int hoehe = (int) (Math.sqrt(3) / 2 * seite);

      lblFlaeche.setText("" + flaeche);
      lblUmfang.setText("" + umfang);
      lblHoehe.setText("" + hoehe);

      dreieckPanel.setSeite(seite);
      dreieckPanel.setHoehe(hoehe);
      dreieckPanel.repaint();
  }//GEN-LAST:event_btnZeichneActionPerformed

    public JLabel getLblHoehe() {
        return lblHoehe;
    }

    public void setLblHoehe(JLabel lblHoehe) {
        this.lblHoehe = lblHoehe;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnZeichne;
    private javax.swing.JLabel lblFlaeche;
    private javax.swing.JLabel lblFlaecheText;
    private javax.swing.JLabel lblHoehe;
    private javax.swing.JLabel lblHoeheText;
    private javax.swing.JLabel lblSeiteText;
    private javax.swing.JLabel lblTitelText;
    private javax.swing.JLabel lblUmfang;
    private javax.swing.JLabel lblUmfangText;
    private javax.swing.JPanel pnlZeichnen;
    private javax.swing.JTextField txtSeite;
    // End of variables declaration//GEN-END:variables
}
